### PR TITLE
Use File.open with a block for simple exception handling and ensuring files are closed

### PR DESCRIPTION
**Pull request by pgwillia**
## Context

@beausapach asked "Is there a process that's holding the file open?  The space may not be freed until it's closed, which would happen at shutdown."

With no associated block, `File.open` is a synonym for `File.new`.  The `new` method returns a `File` instance that you can then read or write from. The file remains open until `close` is called on the instance. Once the file variable goes out of scope, then garbage collection will eventually close it, but this may not happen for a while. Meanwhile, resources are being held open.  (From [Ruby 3.3: Opening and Closing Files](https://learning.oreilly.com/library/view/programming-ruby-3-3/9798888650684/f_0082.xhtml#d25e38151))

Related to #475 

## What's New

Use File.open with a block for simple exception handling and ensuring files are closed

### CODE REVIEW

**Review by ConnorSheremeta — DISMISSED** [review]
All looks good to me! :+1:

**Comment by ConnorSheremeta** [comment]
> All looks good to me! 👍

Noticing now that PMPY has a changelog that this could be added to: https://github.com/ualbertalib/pushmi_pullyu/blob/main/CHANGELOG.md

**Comment by pgwillia** [comment]
> > All looks good to me! 👍
> 
> Noticing now that PMPY has a changelog that this could be added to: https://github.com/ualbertalib/pushmi_pullyu/blob/main/CHANGELOG.md

Nice call out!  I've now updated the CHANGELOG.

**Review by ConnorSheremeta — APPROVED** [review]
LGTM!

**Pull request merged**
